baseURL = 'https://painting.pixelastic.com/'
languageCode = 'en-us'
title = 'Pixelastic Painting Log'
disablePathToLower = true

[params]
description = "Documenting my journey through miniature painting and terrain building."
keywords = "terrain crafting, dungeon tiles, miniature painting, speedpaints, dip painting, dungeons and dragons, pathfinder, tabletop rpg, scatter terrain, foam crafting"

[build]
[build.buildStats]
# Generate ./hugo_stats.json that contains all class names.
# This is used as a source for Tailwind
enable = true

# Rebuild CSS...
[[build.cachebusters]]
# ...whenever an HTML file is updated
target = "css"
source = "layouts/.*\\.html"

[[build.cachebusters]]
# ...whenever a CSS file is updated
target = "css"
source = "assets/src/.*\\.css"

[permalinks]
posts = '/:contentbasename/'

[pagination]
pagerSize = 12

[taxonomies]
tag = 'tags'

[outputs]
home = ['HTML', 'RSS']
page = ['HTML']
taxonomy = ['HTML']
term = ['HTML']

# Make screenshotWarm display as JSON
[outputFormats.screenshotWarm]
mediaType = 'application/json'
baseName = 'screenshotWarm'
isPlainText = true

[markup]
[markup.goldmark]
[markup.goldmark.renderer]
unsafe = true # Allow HTML in markdown

[minify]
disableJSON = true

# Allow some specific env variables, used for cachebusting of og:image
# screenshots
[security]
[security.funcs]
getenv = ['^BUILD_ID$']
