# Build website with Hugo
[build]
command = "yarn run build:prod"
publish = "public"

[build.environment]
HUGO_VERSION = "0.160.1"

# Terry Pratchett homage
[[headers]]
for = "/*"
[headers.values]
X-Clacks-Overhead = "GNU Terry Pratchett"
