#!/usr/bin/env zsh
setopt NULL_GLOB
set -e

local targetDirectory="$1"

# Convert relative path to absolute path
targetDirectory="$(cd "$targetDirectory" && pwd)"

for imageFile in "$targetDirectory"/*.{png,jpg,jpeg,gif,webp}; do
  local imageName=$(basename "$imageFile")

  # Check if image is referenced in index.md
  grep -q "$imageName" "${targetDirectory}/index.md" || rm "$imageFile"
done
