#!/usr/bin/env zsh
# Build the site locally

# Initialize GVM
[[ -s ~/.gvm/scripts/gvm ]] && source ~/.gvm/scripts/gvm

# Stop on errors only once GVM is loaded
set -e

# Build for production
hugo --minify --environment production
