#!/usr/bin/env bash
# Build the site for production

# Load hugo from GVM if not available
if ! command -v hugo >/dev/null; then
  source "$HOME/.gvm/scripts/gvm" >/dev/null
fi

# Generate unique build ID for cache busting
export BUILD_ID=$(date +%s)

# Build for production
hugo --minify --environment production
