#!/usr/bin/env zsh
# Serve local website

# Initialize GVM
[[ -s ~/.gvm/scripts/gvm ]] && source ~/.gvm/scripts/gvm

# Stop on errors only once GVM is loaded
set -e

# Hugo dev server with integrated Tailwind CSS processing
hugo server \
  --buildDrafts \
  --buildFuture \
  --openBrowser
