#!/usr/bin/env zsh
# Serve local website

# Initialize GVM
[[ -s ~/.gvm/scripts/gvm ]] && source ~/.gvm/scripts/gvm

# Stop on errors only once GVM is loaded
set -e

# Tailwind
npx tailwindcss -i ./assets/css/main.css -o ./assets/css/style.css --watch &
TAILWIND_PID=$!

# Hugo
hugo server --buildDrafts --buildFuture --openBrowser

# Clean up
kill $TAILWIND_PID 2>/dev/null || true
